/home/user/miniconda/envs/py36/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: [33mWARN: Box bound precision lowered by casting to float32[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
  0%|                                                                                                                                                                              | 0/1000 [00:00<?, ?it/s]  0%|                                                                                                                                                                              | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/bayes_opt/target_space.py", line 191, in probe
    target = self._cache[_hashable(x)]
KeyError: (0.3753256340122696, 0.6482948408530079)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_ac_mcc.py", line 270, in <module>
    n_iter=10,
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py", line 174, in maximize
    self.probe(x_probe, lazy=False)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py", line 112, in probe
    self._space.probe(params)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/bayes_opt/target_space.py", line 194, in probe
    target = self.target_func(**params)
  File "main_ac_mcc.py", line 139, in main
    fuck -= math.pow(action[0], 2) * 0.1
NameError: name 'math' is not defined
